### ISSUE TITLE
How to get the instagram thread ID ?

### ISSUE THREAD

**Issue by FaizaanMeghani** [jake-walker/instagram-discord-bridge#1]
Hello,

How do we get the Instagram thread ID please ? 
I know how to get it on Discord but I don't know how on Instagram.

Thank's

**Comment by jake-walker** [comment]
Hey @FaizaanMeghani,

Thanks for your interest! There is a feature that I made for this, but it's not documented at the moment. After setting up the configuration file just with an Instagram username and password like so:

```yaml
module.exports = {
  instagram: {
    username: "myinstagramusername",
    password: "password"
  },
  discord: {
    token: "xxx"
  },
  mappings: [], // **NO MAPPINGS ARE REQUIRED
  webhooks: {} // **NO WEBHOOKS ARE REQUIRED
}
```

Then start the bot with `node index.js` and you get the following output:
![](https://user-images.githubusercontent.com/10981005/62211517-9d7a1200-b396-11e9-9c88-ebbc01a66e7d.png)

With that, you can find the thread that you want to use and find the ID of it for use in the configuration file. For example, for my chat I would add a mapping like this:

```yaml
{
  instagram: "34028236684...",
  discord: "49457849..."
}
```

Hope that helps!
